import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

import { ClientAuthProvider } from "@/context/ClientAuthProvider";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    trackCustomEvent: (eventName: string) => void;
  }
}

// added it to pass the backend URL to the script.js file
const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL || "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Inject the backend URL as a meta tag */}
        <meta name="backend-url" content={backendUrl} />
      </head>
      <Script crossOrigin="anonymous" src="/static/script.js"></Script>
      <Script
        crossOrigin="anonymous"
        strategy="lazyOnload"
        src="/static/events.js"
      ></Script>
      <body className={inter.className}>
        <ClientAuthProvider>
          <Navbar />
          <main className="mt-14 max-w-5xl mx-auto">{children}</main>
        </ClientAuthProvider>
      </body>
    </html>
  );
}
